require "user.options"
require "user.plugins"
require "user.colorscheme"
require "user.lsp"
require "user.keymaps"


-- Plugin
require "user.which-key"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.bufferline"
require "user.lualine"
require "user.nvim_tree"
require "user.comment"
require "user.nvim-colorizer"
require "user.competitest"
require "user.indent_blankline"
-- require "user.satellite"
